databases:
  - name: leopardland
    databaseName: leopardland
    user: leopardland
    plan: free

services:
  - type: web
    name: otree-web
    env: python
    plan: free
    buildCommand: "chmod +x start.sh && pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leopardland
          property: connectionString
      - key: OTREE_PRODUCTION
        value: 1
